### PR TITLE
55 ng jquery breaks in heroku

### LINKED ISSUE #55: Look into heroku compiling jquery calendar
Click on the calendars on padcrash.herokuapp.com

### PR DESCRIPTION
**Pull request by njgheorghita**
Fixed bug with jquery datepicker not working in production/heroku

closes #55

### CODE REVIEW

File: app/assets/javascripts/application.js [hunk 1]
```diff
@@ -11,7 +11,7 @@
 // about supported directives.
 //
 //= require jquery
-//= require bootstrap-sprockets
-//= require jquery_ujs
 //= require jquery-ui
+//= require jquery_ujs
```
Comment (tmikeschu) [inline app/assets/javascripts/application.js:15]: I know moving these two lines require a lot of research. Thanks for trudging! @njgheorghita

**Review by tmikeschu — COMMENTED** [review]
Thank you 🙏

File: app/assets/javascripts/application.js (hunk 1 above)
Comment (ski-climb) [reply app/assets/javascripts/application.js:15]: Second that!
